"""Repository interface (Protocol). The SQLite driver implements this; a Turso
driver can implement the same surface later. Callers depend on this, not sqlite.
"""
from __future__ import annotations

from typing import Optional, Protocol, runtime_checkable

from ..models import Draft, Metrics, Post, Score


@runtime_checkable
class Repository(Protocol):
    def init_schema(self) -> None: ...

    # --- posts + metrics ---
    def upsert_post(self, post: Post) -> None: ...
    def add_metrics(self, tweet_id: str, metrics: Metrics) -> None: ...
    def get_post(self, tweet_id: str) -> Optional[Post]: ...
    def recent_posts(self, within_hours: float = 72) -> list[Post]: ...
    def max_seen_tweet_id(self) -> Optional[str]: ...
    def metrics_history(self, tweet_id: str) -> list[Metrics]: ...

    # --- scoring + candidate state ---
    def save_score(self, score: Score) -> None: ...
    def get_score(self, tweet_id: str) -> Optional[Score]: ...
    def set_candidate(self, tweet_id: str, status: str, skip_reason: str = "") -> None: ...
    def candidates(self, status: str) -> list[str]: ...

    # --- drafts / review queue ---
    def add_draft(self, draft: Draft, status: str = "pending") -> int: ...
    def expire_stale_drafts(self, max_age_hours: float) -> int: ...
    def pending_drafts(self) -> list[tuple[int, Draft, Post]]: ...
    def get_draft(self, draft_id: int) -> Optional[tuple[Draft, Post]]: ...
    def set_draft_status(self, draft_id: int, status: str, note: str = "") -> None: ...

    # --- posted log (dedup source of truth) ---
    def has_posted(self, source_tweet_id: str) -> bool: ...
    def posted_authors_since(self, days: int) -> set[str]: ...
    def posted_source_texts(self) -> list[str]: ...
    def log_posted(self, source_tweet_id: str, our_tweet_id: str,
                   author_handle: str, source_text: str, commentary: str) -> None: ...
    def count_posted_today(self) -> int: ...

    # --- key/value state ---
    def get_state(self, key: str, default: str = "") -> str: ...
    def set_state(self, key: str, value: str) -> None: ...
